import { catalogTools } from "./catalog";

export type Tool = {
  slug: string;
  name: string;
  description: string;
  category: string;
  categoryName: string;
  keywords: string[];
  popular?: boolean;
};

export const tools: Tool[] = [
  {
    slug: "take-home-pay",
    name: "手取り計算",
    description:
      "給与明細の支給額、社会保険料、税金を入力して月ごとの手取り額を計算します。",
    category: "work",
    categoryName: "給与・税金",
    keywords: ["手取り計算", "給料 手取り", "年収 手取り", "給与計算"],
    popular: true,
  },
  {
    slug: "income-tax",
    name: "所得税計算",
    description:
      "給与収入から所得税の目安を計算します。給与所得控除・基礎控除を考慮した簡易計算です。",
    category: "work",
    categoryName: "給与・税金",
    keywords: ["所得税", "所得税計算", "給与所得", "税金"],
    popular: true,
  },
  {
    slug: "resident-tax",
    name: "住民税計算",
    description: "前年の所得をもとに住民税の目安を確認できます。",
    category: "work",
    categoryName: "給与・税金",
    keywords: ["住民税", "住民税計算", "市民税", "県民税"],
    popular: true,
  },
  {
    slug: "social-insurance",
    name: "社会保険料計算",
    description:
      "標準報酬月額をもとに健康保険・厚生年金などの負担額の目安を計算します。",
    category: "work",
    categoryName: "給与・税金",
    keywords: ["社会保険", "社会保険料", "健康保険", "厚生年金"],
    popular: true,
  },
  {
    slug: "overtime-pay",
    name: "残業代計算",
    description:
      "時給と残業時間から残業代の目安を計算します。割増率を指定できます。",
    category: "work",
    categoryName: "給与・税金",
    keywords: ["残業代", "残業代計算", "割増賃金", "時間外労働"],
    popular: true,
  },
  {
    slug: "hourly-wage",
    name: "時給計算",
    description:
      "月給と勤務時間から実質時給を計算します。月収から時給を知りたいときに便利です。",
    category: "work",
    categoryName: "給与・税金",
    keywords: ["時給計算", "時給", "月給 時給", "給与"],
    popular: true,
  },
  {
    slug: "salary-take-home",
    name: "給与手取り計算",
    description:
      "年収から所得税、住民税、社会保険料を考慮した月の手取り額を概算します。",
    category: "work",
    categoryName: "給与・税金",
    keywords: [
      "給与手取り計算",
      "給料 手取り 計算",
      "年収 手取り",
      "月の手取り",
    ],
    popular: true,
  },
  {
    slug: "pension-premium",
    name: "厚生年金計算",
    description: "標準報酬月額から厚生年金保険料の本人負担額を概算します。",
    category: "work",
    categoryName: "給与・税金",
    keywords: ["厚生年金計算", "厚生年金 保険料", "年金保険料"],
  },
  {
    slug: "employment-insurance",
    name: "雇用保険料計算",
    description: "月の賃金と労働者負担率から雇用保険料を計算します。",
    category: "work",
    categoryName: "給与・税金",
    keywords: ["雇用保険 計算", "雇用保険料", "雇用保険料計算"],
  },
  {
    slug: "annual-monthly",
    name: "年収・月収換算",
    description: "年収とボーナスから月収の目安を換算します。",
    category: "work",
    categoryName: "給与・税金",
    keywords: ["年収 月収", "年収 月収換算", "月収 計算"],
  },
  {
    slug: "paid-leave",
    name: "有給休暇計算",
    description: "勤続年数と取得済み日数から有給休暇の残日数目安を確認します。",
    category: "work",
    categoryName: "給与・税金",
    keywords: ["有給休暇 計算", "有給 残日数"],
  },
  {
    slug: "overtime-hours",
    name: "残業時間計算",
    description: "1日の残業時間と日数から合計残業時間を計算します。",
    category: "work",
    categoryName: "給与・税金",
    keywords: ["残業時間 計算", "残業時間"],
  },
  {
    slug: "night-overtime",
    name: "深夜残業計算",
    description: "深夜帯の勤務時間から深夜残業代の目安を計算します。",
    category: "work",
    categoryName: "給与・税金",
    keywords: ["深夜残業 計算", "深夜手当"],
  },
  {
    slug: "holiday-work",
    name: "休日出勤計算",
    description: "休日出勤の時間と日数から手当の目安を計算します。",
    category: "work",
    categoryName: "給与・税金",
    keywords: ["休日出勤 計算", "休日出勤 手当"],
  },
  {
    slug: "resignation-date",
    name: "退職日計算",
    description: "退職を伝える日から退職日の目安を確認します。",
    category: "work",
    categoryName: "給与・税金",
    keywords: ["退職日 計算", "退職 いつ"],
  },
  {
    slug: "service-years",
    name: "勤続年数計算",
    description: "入社日から勤続年数を計算します。",
    category: "work",
    categoryName: "給与・税金",
    keywords: ["勤続年数 計算", "入社年数"],
  },
  {
    slug: "childcare-benefit",
    name: "育児休業給付金計算",
    description: "休業前の賃金から育児休業給付金の目安を計算します。",
    category: "work",
    categoryName: "給与・税金",
    keywords: ["育児休業給付金", "育休 給付金 計算"],
  },
  {
    slug: "maternity-leave",
    name: "産休期間計算",
    description: "出産予定日から産前産後休業の期間目安を計算します。",
    category: "work",
    categoryName: "給与・税金",
    keywords: ["産休期間", "産前産後休業 計算"],
  },
  {
    slug: "age-calculator",
    name: "年齢計算",
    description: "生年月日から現在または指定日の年齢を計算します。",
    category: "date",
    categoryName: "日付・時間",
    keywords: ["年齢計算", "年齢", "誕生日"],
  },
  {
    slug: "japanese-era",
    name: "和暦・西暦変換",
    description: "西暦を令和・平成・昭和の和暦に変換します。",
    category: "date",
    categoryName: "日付・時間",
    keywords: ["和暦 西暦 変換", "令和 何年"],
  },
  {
    slug: "zodiac",
    name: "干支計算",
    description: "西暦から十二支を確認します。",
    category: "date",
    categoryName: "日付・時間",
    keywords: ["干支 計算", "十二支"],
  },
  {
    slug: "month-edges",
    name: "月初・月末計算",
    description: "指定した月の月初日と月末日を確認します。",
    category: "date",
    categoryName: "日付・時間",
    keywords: ["月末 計算", "月初", "月末日"],
  },
  {
    slug: "japanese-holiday",
    name: "祝日計算",
    description: "指定した日が日本の主な祝日かどうかを確認します。",
    category: "date",
    categoryName: "日付・時間",
    keywords: ["祝日 計算", "今日は祝日", "日本の祝日"],
  },
  {
    slug: "date-difference",
    name: "日付差計算",
    description: "2つの日付の経過日数をすばやく計算します。",
    category: "date",
    categoryName: "日付・時間",
    keywords: ["日付差", "日数計算"],
  },
  {
    slug: "date-add-subtract",
    name: "日付計算",
    description: "指定した日数を日付に加算・減算します。",
    category: "date",
    categoryName: "日付・時間",
    keywords: ["何日後", "何日前", "日付計算"],
  },
  {
    slug: "business-days",
    name: "営業日計算",
    description: "土日を除いた平日の営業日数を計算します。",
    category: "date",
    categoryName: "日付・時間",
    keywords: ["営業日", "平日", "日数"],
  },
  {
    slug: "tax-calculator",
    name: "税込・税抜計算",
    description: "10%・8%の消費税を含む金額と税抜金額を計算します。",
    category: "money",
    categoryName: "お金・節約",
    keywords: ["税込", "税抜", "消費税"],
  },
  {
    slug: "discount-calculator",
    name: "割引計算",
    description: "割引率から割引額と割引後価格を計算します。",
    category: "money",
    categoryName: "お金・節約",
    keywords: ["割引", "値引き"],
  },
  {
    slug: "split-bill",
    name: "割り勘計算",
    description: "合計金額を人数で割り、1人あたりの支払額を計算します。",
    category: "money",
    categoryName: "お金・節約",
    keywords: ["割り勘", "飲み会", "支払い"],
  },
  {
    slug: "gas-cost",
    name: "ガソリン代計算",
    description: "走行距離・燃費・ガソリン価格から交通費を計算します。",
    category: "life",
    categoryName: "生活・交通",
    keywords: ["ガソリン代", "燃費", "交通費"],
  },
  {
    slug: "electricity-cost",
    name: "電気代計算",
    description: "消費電力と使用時間から電気料金の目安を計算します。",
    category: "life",
    categoryName: "生活・交通",
    keywords: ["電気代", "電気料金", "消費電力"],
  },
  {
    slug: "mortgage",
    name: "住宅ローン計算",
    description:
      "借入金額、金利、返済期間から毎月の住宅ローン返済額を計算します。",
    category: "life",
    categoryName: "生活・交通",
    keywords: ["住宅ローン 計算", "ローン返済", "毎月返済額"],
    popular: true,
  },
  {
    slug: "rent-initial-cost",
    name: "家賃初期費用計算",
    description:
      "敷金・礼金・仲介手数料を含む賃貸契約時の初期費用を概算します。",
    category: "life",
    categoryName: "生活・交通",
    keywords: ["引越し 初期費用", "家賃 初期費用", "敷金 礼金"],
  },
  {
    slug: "moving-cost",
    name: "引越し費用計算",
    description: "人数、移動距離、時期から引越し費用の目安を計算します。",
    category: "life",
    categoryName: "生活・交通",
    keywords: ["引越し 費用", "引越し見積もり", "単身 引越し"],
  },
  {
    slug: "gas-bill",
    name: "ガス代計算",
    description: "使用量、基本料金、従量料金から月のガス代を計算します。",
    category: "life",
    categoryName: "生活・交通",
    keywords: ["ガス代", "ガス料金", "都市ガス"],
  },
  {
    slug: "water-bill",
    name: "水道代計算",
    description: "使用量、基本料金、従量料金から月の水道代を計算します。",
    category: "life",
    categoryName: "生活・交通",
    keywords: ["水道代", "水道料金", "水道 使用量"],
  },
  {
    slug: "deposit-key-money",
    name: "敷金・礼金計算",
    description: "家賃と月数から敷金・礼金の合計を計算します。",
    category: "life",
    categoryName: "生活・交通",
    keywords: ["敷金 礼金 計算", "賃貸 初期費用"],
  },
  {
    slug: "rent-income-ratio",
    name: "家賃手取り比率計算",
    description: "月の家賃が手取りに占める割合を計算します。",
    category: "life",
    categoryName: "生活・交通",
    keywords: ["家賃 手取り 比率", "適正家賃"],
  },
  {
    slug: "commuter-pass",
    name: "通勤定期比較",
    description: "都度運賃と定期券の金額を比較します。",
    category: "life",
    categoryName: "生活・交通",
    keywords: ["通勤定期 比較", "定期券 元が取れる"],
  },
  {
    slug: "car-ownership",
    name: "車維持費計算",
    description: "税金・保険・整備費から車の維持費目安を計算します。",
    category: "life",
    categoryName: "生活・交通",
    keywords: ["車 維持費", "自動車 維持費 計算"],
  },
  {
    slug: "nhk-fee",
    name: "NHK受信料計算",
    description: "月額の受信料から年額の目安を計算します。",
    category: "life",
    categoryName: "生活・交通",
    keywords: ["NHK受信料", "NHK 料金"],
  },
  {
    slug: "due-date",
    name: "出産予定日計算",
    description: "最終月経開始日から出産予定日を計算します。",
    category: "family",
    categoryName: "育児・家族",
    keywords: ["出産予定日 計算", "妊娠 予定日"],
  },
  {
    slug: "pregnancy-weeks",
    name: "妊娠週数計算",
    description: "最終月経開始日から妊娠週数を計算します。",
    category: "family",
    categoryName: "育児・家族",
    keywords: ["妊娠週数 計算", "妊娠 何週"],
  },
  {
    slug: "baby-age",
    name: "月齢計算",
    description: "生年月日から赤ちゃんの月齢を計算します。",
    category: "family",
    categoryName: "育児・家族",
    keywords: ["月齢 計算", "赤ちゃん 月齢"],
  },
  {
    slug: "nursery-age",
    name: "保育園年齢計算",
    description: "生年月日から保育園の年齢区分の目安を確認します。",
    category: "family",
    categoryName: "育児・家族",
    keywords: ["保育園 年齢 計算", "保育園 何歳"],
  },
  {
    slug: "parental-leave",
    name: "育休期間計算",
    description: "生年月日から1年間の育休期間目安を確認します。",
    category: "family",
    categoryName: "育児・家族",
    keywords: ["育休期間", "育児休業 期間"],
  },
  {
    slug: "child-allowance",
    name: "児童手当計算",
    description: "児童数と年齢から児童手当の月額目安を計算します。",
    category: "family",
    categoryName: "育児・家族",
    keywords: ["児童手当 計算", "子ども 手当"],
  },
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    description: "JSONを整形・圧縮して読みやすく表示します。",
    category: "developer",
    categoryName: "IT・開発者",
    keywords: ["JSON", "Formatter", "JSON整形"],
  },
];

const registeredNames = new Set(tools.map((tool) => tool.name));
tools.push(...catalogTools.filter((tool) => !registeredNames.has(tool.name)));

export const categories = [
  {
    slug: "work",
    name: "給与・税金",
    description: "給与、税金、社会保険、残業など仕事とお金に関する計算ツール。",
  },
  {
    slug: "date",
    name: "日付・時間",
    description: "年齢、日付差、営業日など日付に関する便利なツール。",
  },
  {
    slug: "money",
    name: "お金・節約",
    description: "消費税、割引、割り勘など日常のお金を計算するツール。",
  },
  {
    slug: "life",
    name: "生活・交通",
    description: "ガソリン代や電気代など生活にかかる費用を計算するツール。",
  },
  {
    slug: "developer",
    name: "IT・開発者",
    description: "開発作業で使えるオンラインユーティリティ。",
  },
  {
    slug: "family",
    name: "育児・家族",
    description: "妊娠、出産、育休、子育てに役立つ計算ツール。",
  },
];

export function getTool(slug: string) {
  return tools.find((tool) => tool.slug === slug);
}
